/**
 * NFL Desperation server helpers. Server-only (route handlers, server components).
 *
 * Everything that reads another entry's picks goes through buildBoard(), which
 * applies the visibility gates from ./visibility. Do not query nd_picks for
 * "other players" anywhere else.
 */
import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '@/types/database'
import { createClient as createSessionClient } from '@/lib/supabase/server'
import { checkSuperAdmin, checkOrgAdmin, checkPoolCommissioner } from '@/lib/permissions'
import { fetchEspnWeek } from './espn'
import { mapEspnEvent, computeWeekLockAt, pickCurrentWeek, joinWeekFor } from './schedule'
import type { JoinClosedReason } from './join'
export { pickCurrentWeek }
import { scoreWeek, isTerminal, sumSeasonPoints } from './scoring'
import { isWeekLocked } from './visibility'
import type { NdGame, NdWeek, NdPick, Board, BoardEntry } from './types'

type Admin = SupabaseClient<Database>
type Tables = Database['public']['Tables']
export type NdEntryRow = Tables['nd_entries']['Row']
export type NdPoolRow = Tables['nd_pools']['Row']

/** Hex token generated by the DB default: encode(gen_random_bytes(24),'hex') */
const TOKEN_RE = /^[a-f0-9]{48}$/

/** Don't hit ESPN more often than this for the same week. */
const SYNC_THROTTLE_MS = 20_000
/** Lazy sync from page loads only if data is at least this stale. */
const LAZY_SYNC_STALE_MS = 45_000

// ---------------------------------------------------------------------------
// Entry / token
// ---------------------------------------------------------------------------

export interface EntryContext {
  entry: NdEntryRow
  ndPool: NdPoolRow
  pool: { id: string; name: string; status: string; org_id: string }
}

export async function getEntryByToken(admin: Admin, token: string): Promise<EntryContext | null> {
  if (!TOKEN_RE.test(token)) return null

  const { data: entry } = await admin
    .from('nd_entries')
    .select('*')
    .eq('access_token', token)
    .eq('active', true)
    .maybeSingle()
  if (!entry) return null

  const { data: ndPool } = await admin.from('nd_pools').select('*').eq('id', entry.nd_pool_id).single()
  if (!ndPool) return null

  const { data: pool } = await admin
    .from('pools')
    .select('id, name, status, org_id')
    .eq('id', ndPool.pool_id)
    .single()
  if (!pool) return null

  // Presence stamp: drives the "Opened" / "Never opened" status on the commissioner
  // dashboard. Awaited on purpose: the query builder is lazy and never fires
  // unless awaited or .then()'d. Throttled so a busy player isn't a write per call.
  const staleBefore = new Date(Date.now() - 10 * 60 * 1000).toISOString()
  await admin
    .from('nd_entries')
    .update({ last_seen_at: new Date().toISOString() })
    .eq('id', entry.id)
    .or(`last_seen_at.is.null,last_seen_at.lt.${staleBefore}`)

  return { entry, ndPool, pool }
}

export function entryDisplayName(e: Pick<NdEntryRow, 'display_name' | 'email'>): string {
  if (e.display_name?.trim()) return e.display_name.trim()
  return e.email.split('@')[0]
}

/** True when the token belongs to an entry the commissioner has disabled (so the page can say so instead of 404). */
export async function isDisabledEntry(admin: Admin, token: string): Promise<boolean> {
  if (!TOKEN_RE.test(token)) return false
  const { data } = await admin.from('nd_entries').select('id').eq('access_token', token).eq('active', false).maybeSingle()
  return !!data
}

// ---------------------------------------------------------------------------
// Public self-join
// ---------------------------------------------------------------------------

export interface JoinState {
  open: boolean
  reason: JoinClosedReason | null
  /** Week a joiner would start competing in; null when unknown or the season is over */
  joinWeek: number | null
  weeks: NdWeek[]
}

/** Can someone holding the pool's public link create their own entry right now? */
export async function getJoinState(admin: Admin, ndPool: NdPoolRow, poolStatus: string, now: Date = new Date()): Promise<JoinState> {
  const weeks = await getWeeks(admin, ndPool.season_year)
  const joinWeek = joinWeekFor(weeks, now)
  const closed = (reason: JoinClosedReason): JoinState => ({ open: false, reason, joinWeek, weeks })
  if (poolStatus !== 'open') return closed('pool_closed')
  if (!ndPool.self_join_enabled) return closed('self_join_off')
  if (weeks.length === 0) return closed('no_schedule')
  if (joinWeek === null) return closed('season_over')
  if (joinWeek > 1 && !ndPool.allow_midseason_join) return closed('midseason_closed')
  return { open: true, reason: null, joinWeek, weeks }
}

// ---------------------------------------------------------------------------
// Commissioner auth for dashboard-side routes
// ---------------------------------------------------------------------------

export type CommissionerCheck =
  | { ok: true; userId: string; email: string | null; displayName: string | null; ndPool: NdPoolRow; pool: { id: string; org_id: string; name: string } }
  | { ok: false; status: number; error: string }

export async function requireCommissioner(admin: Admin, ndPoolId: string): Promise<CommissionerCheck> {
  const session = await createSessionClient()
  const { data: { user } } = await session.auth.getUser()
  if (!user) return { ok: false, status: 401, error: 'Unauthorized' }

  const { data: ndPool } = await admin.from('nd_pools').select('*').eq('id', ndPoolId).single()
  if (!ndPool) return { ok: false, status: 404, error: 'Pool not found' }
  const { data: pool } = await admin.from('pools').select('id, org_id, name').eq('id', ndPool.pool_id).single()
  if (!pool) return { ok: false, status: 404, error: 'Pool not found' }

  const [{ data: profile }, { data: orgMembership }, { data: poolMembership }] = await Promise.all([
    session.from('profiles').select('is_super_admin, display_name').eq('id', user.id).single(),
    session.from('org_memberships').select('role').eq('org_id', pool.org_id).eq('user_id', user.id).maybeSingle(),
    session.from('pool_memberships').select('role').eq('pool_id', pool.id).eq('user_id', user.id).maybeSingle(),
  ])
  const isSuperAdmin = checkSuperAdmin(profile)
  const isOrgAdmin = checkOrgAdmin(orgMembership, isSuperAdmin)
  if (!checkPoolCommissioner(poolMembership, isOrgAdmin)) {
    return { ok: false, status: 403, error: 'Commissioner access required' }
  }
  return { ok: true, userId: user.id, email: user.email?.toLowerCase() ?? null, displayName: profile?.display_name ?? null, ndPool, pool }
}

/** Super admin OR commissioner of any ND pool in the season. For shared-schedule writes. */
export async function requireSeasonCommissioner(admin: Admin, seasonYear: number): Promise<{ ok: true; userId: string } | { ok: false; status: number; error: string }> {
  const session = await createSessionClient()
  const { data: { user } } = await session.auth.getUser()
  if (!user) return { ok: false, status: 401, error: 'Unauthorized' }
  const { data: allowed } = await session.rpc('is_nd_season_commissioner', { p_season: seasonYear })
  if (!allowed) return { ok: false, status: 403, error: 'Commissioner access required' }
  return { ok: true, userId: user.id }
}

// ---------------------------------------------------------------------------
// Weeks & games
// ---------------------------------------------------------------------------

export async function getWeeks(admin: Admin, seasonYear: number): Promise<NdWeek[]> {
  const { data } = await admin
    .from('nd_weeks')
    .select('id, season_year, week_number, lock_at, first_kickoff_at, last_kickoff_at, status, finalized_at')
    .eq('season_year', seasonYear)
    .order('week_number')
  return (data ?? []) as NdWeek[]
}

export async function getWeekGames(admin: Admin, seasonYear: number, week: number): Promise<NdGame[]> {
  const { data } = await admin
    .from('nd_games')
    .select('id, season_year, week_number, espn_game_id, home_team, home_abbr, home_logo, away_team, away_abbr, away_logo, kickoff_at, venue, neutral_site, home_score, away_score, status, period, clock, winner, qualifies, last_synced_at, spread, over_under, odds_details, odds_provider')
    .eq('season_year', seasonYear)
    .eq('week_number', week)
    .order('kickoff_at')
  return (data ?? []) as NdGame[]
}

// ---------------------------------------------------------------------------
// ESPN sync
// ---------------------------------------------------------------------------

/**
 * Import/refresh a week's schedule from ESPN. Upserts nd_weeks + nd_games.
 * If ESPN moved a game to a different week (Rule 8), picks on it are deleted.
 */
export async function syncScheduleWeek(admin: Admin, seasonYear: number, week: number) {
  const board = await fetchEspnWeek(seasonYear, week)
  const mapped = (board.events ?? [])
    .map((e) => mapEspnEvent(e, seasonYear, week))
    .filter((g): g is NonNullable<typeof g> => g !== null)

  if (mapped.length === 0) return { games: 0, movedGames: 0 }

  const kickoffs = mapped.map((g) => g.kickoff_at)
  const lockAt = computeWeekLockAt(kickoffs)
  const first = kickoffs.reduce((a, b) => (a < b ? a : b))
  const last = kickoffs.reduce((a, b) => (a > b ? a : b))

  const { error: weekErr } = await admin.from('nd_weeks').upsert(
    {
      season_year: seasonYear,
      week_number: week,
      lock_at: lockAt.toISOString(),
      first_kickoff_at: first,
      last_kickoff_at: last,
    },
    { onConflict: 'season_year,week_number' }
  )
  if (weekErr) throw new Error(`nd_weeks upsert: ${weekErr.message}`)

  // Detect games that moved weeks so their picks can be cleared (Rule 8)
  const { data: existing } = await admin
    .from('nd_games')
    .select('id, espn_game_id, week_number')
    .eq('season_year', seasonYear)
    .in('espn_game_id', mapped.map((g) => g.espn_game_id))
  const moved = (existing ?? []).filter((e) => e.week_number !== week)

  const now = new Date().toISOString()
  const { error: gamesErr } = await admin.from('nd_games').upsert(
    mapped.map((g) => ({ ...g, last_synced_at: now })),
    { onConflict: 'season_year,espn_game_id' }
  )
  if (gamesErr) throw new Error(`nd_games upsert: ${gamesErr.message}`)

  if (moved.length > 0) {
    await admin.from('nd_picks').delete().in('game_id', moved.map((m) => m.id))
  }

  await refreshWeekStatus(admin, seasonYear, week)
  return { games: mapped.length, movedGames: moved.length }
}

/**
 * Refresh live scores for a week from ESPN, then recompute scores + week status.
 * Throttled: returns { synced: false } if the week was synced within the last 20s.
 */
export async function syncScoresWeek(admin: Admin, seasonYear: number, week: number, opts: { force?: boolean } = {}) {
  const games = await getWeekGames(admin, seasonYear, week)
  if (games.length === 0) return { synced: false, reason: 'no games' as const }

  const newest = Math.max(...games.map((g) => (g.last_synced_at ? new Date(g.last_synced_at).getTime() : 0)))
  if (!opts.force && Date.now() - newest < SYNC_THROTTLE_MS) {
    return { synced: false, reason: 'throttled' as const }
  }

  const board = await fetchEspnWeek(seasonYear, week)
  const now = new Date().toISOString()
  const byEspn = new Map(games.map((g) => [g.espn_game_id, g]))

  const updates = (board.events ?? [])
    .map((e) => mapEspnEvent(e, seasonYear, week))
    .filter((g): g is NonNullable<typeof g> => g !== null && byEspn.has(g.espn_game_id))

  await Promise.all(
    updates.map((g) =>
      admin
        .from('nd_games')
        .update({
          home_score: g.home_score,
          away_score: g.away_score,
          status: g.status,
          period: g.period,
          clock: g.clock,
          winner: g.winner,
          qualifies: g.qualifies,
          kickoff_at: g.kickoff_at, // flexed/postponed times
          last_synced_at: now,
          // Line drifts all week; refresh it, but don't wipe a known line if ESPN omits odds
          ...(g.odds_details !== null
            ? { spread: g.spread, over_under: g.over_under, odds_details: g.odds_details, odds_provider: g.odds_provider }
            : {}),
        })
        .eq('season_year', seasonYear)
        .eq('espn_game_id', g.espn_game_id)
    )
  )

  await recomputeWeekScores(admin, seasonYear, week)
  await refreshWeekStatus(admin, seasonYear, week)
  return { synced: true, reason: 'ok' as const, updated: updates.length }
}

/** True if a page load should trigger a score refresh before rendering. */
export function shouldLazySync(games: NdGame[], now: Date = new Date()): boolean {
  if (games.length === 0) return false
  const active = games.some(
    (g) => g.status === 'in_progress' || (g.status === 'scheduled' && new Date(g.kickoff_at) <= now)
  )
  if (!active) return false
  const newest = Math.max(...games.map((g) => (g.last_synced_at ? new Date(g.last_synced_at).getTime() : 0)))
  return now.getTime() - newest > LAZY_SYNC_STALE_MS
}

async function refreshWeekStatus(admin: Admin, seasonYear: number, week: number) {
  const games = await getWeekGames(admin, seasonYear, week)
  const { data: w } = await admin
    .from('nd_weeks')
    .select('lock_at, status')
    .eq('season_year', seasonYear)
    .eq('week_number', week)
    .single()
  if (!w || games.length === 0) return

  const now = new Date()
  let status: NdWeek['status']
  const allTerminal = games.every(isTerminal)
  if (allTerminal) status = 'final'
  else if (games.some((g) => g.status === 'in_progress' || (g.status === 'final'))) status = 'in_progress'
  else if (now >= new Date(w.lock_at)) status = 'locked'
  else if (games.some((g) => new Date(g.kickoff_at) <= now)) status = 'in_progress'
  else status = 'open'

  const patch: Tables['nd_weeks']['Update'] = { status }
  if (status === 'final' && w.status !== 'final') patch.finalized_at = now.toISOString()
  await admin.from('nd_weeks').update(patch).eq('season_year', seasonYear).eq('week_number', week)
}

// ---------------------------------------------------------------------------
// Scores
// ---------------------------------------------------------------------------

/** Recompute nd_week_scores for every entry in every pool of this season. */
export async function recomputeWeekScores(admin: Admin, seasonYear: number, week: number) {
  const games = await getWeekGames(admin, seasonYear, week)
  if (games.length === 0) return
  const gameIds = games.map((g) => g.id)
  const finalized = games.every(isTerminal)

  const { data: pools } = await admin.from('nd_pools').select('id').eq('season_year', seasonYear)
  if (!pools?.length) return
  const { data: entries } = await admin
    .from('nd_entries')
    .select('id')
    .in('nd_pool_id', pools.map((p) => p.id))
  if (!entries?.length) return

  const { data: picks } = await admin
    .from('nd_picks')
    .select('entry_id, game_id, selection')
    .in('game_id', gameIds)

  const byEntry = new Map<string, NdPick[]>()
  for (const p of picks ?? []) {
    const list = byEntry.get(p.entry_id) ?? []
    list.push({ game_id: p.game_id, selection: p.selection as NdPick['selection'] })
    byEntry.set(p.entry_id, list)
  }

  const rows: Tables['nd_week_scores']['Insert'][] = entries.map((e) => {
    const s = scoreWeek(byEntry.get(e.id) ?? [], games)
    return {
      entry_id: e.id,
      season_year: seasonYear,
      week_number: week,
      picks_made: s.picksMade,
      qualifying_picks: s.qualifying,
      correct_picks: s.correct,
      is_perfect: s.complete && !s.busted && s.qualifying > 0,
      points: s.finalPoints ?? 0,
      finalized,
      computed_at: new Date().toISOString(),
    }
  })

  const { error } = await admin.from('nd_week_scores').upsert(rows, { onConflict: 'entry_id,season_year,week_number' })
  if (error) throw new Error(`nd_week_scores upsert: ${error.message}`)
}

// ---------------------------------------------------------------------------
// Board — the ONLY place other entries' picks are read
// ---------------------------------------------------------------------------

export async function buildBoard(
  admin: Admin,
  ctx: EntryContext,
  week: NdWeek,
  games: NdGame[],
  now: Date = new Date()
): Promise<Board> {
  const { data: entries } = await admin
    .from('nd_entries')
    .select('id, email, display_name')
    .eq('nd_pool_id', ctx.ndPool.id)
    .eq('active', true)
    .order('created_at')
  const entryIds = (entries ?? []).map((e) => e.id)

  const gameIds = games.map((g) => g.id)
  const { data: picks } = gameIds.length && entryIds.length
    ? await admin.from('nd_picks').select('entry_id, game_id, selection').in('entry_id', entryIds).in('game_id', gameIds)
    : { data: [] as Array<{ entry_id: string; game_id: string; selection: string }> }

  // Season total = finalized weeks only (see sumSeasonPoints)
  const { data: seasonScores } = entryIds.length
    ? await admin
        .from('nd_week_scores')
        .select('entry_id, points, finalized')
        .in('entry_id', entryIds)
        .eq('season_year', ctx.ndPool.season_year)
        .eq('finalized', true)
    : { data: [] as Array<{ entry_id: string; points: number; finalized: boolean }> }
  const seasonTotals = sumSeasonPoints(seasonScores ?? [])

  // One gate for everything about other entries: locked week → all visible
  const weekVisible = isWeekLocked(week, now)

  const picksByEntry = new Map<string, NdPick[]>()
  for (const p of picks ?? []) {
    const list = picksByEntry.get(p.entry_id) ?? []
    list.push({ game_id: p.game_id, selection: p.selection as NdPick['selection'] })
    picksByEntry.set(p.entry_id, list)
  }

  const boardEntries: BoardEntry[] = (entries ?? []).map((e) => {
    const isMe = e.id === ctx.entry.id
    const all = picksByEntry.get(e.id) ?? []
    const show = isMe || weekVisible
    return {
      id: e.id,
      name: entryDisplayName(e),
      isMe,
      pickCount: show ? all.length : null,
      picks: show ? Object.fromEntries(all.map((p) => [p.game_id, p.selection])) : {},
      score: show ? scoreWeek(all, games) : null,
      seasonPoints: seasonTotals.get(e.id) ?? 0,
    }
  })

  return { week, games, countsVisible: weekVisible, entries: boardEntries }
}
